<?php
$pages = $block->getPages();

?>

<h3>
    <?= $block->getTitle() ?>
</h3>

<ul class="page-list">
    <?php foreach ($pages as $page) : ?>
        <li class="page-list-item">
            <!-- Following PSR-2 guide make sure line doesn't exceed 120 chars, don't be afraid to add line breaks -->
            <a class="page-link" href="<?= $block->getUrl($page->getIdentifier()) ?>">
                <?= $page->getTitle(); ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>