<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

?>
<?php if ($_additional = $block->getAdditionalData()) : ?>
    <div class="additional-attributes-wrapper table-wrapper">

        <table class="data table additional-attributes" id="product-attribute-specs-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('More Information')) ?></caption>
            <ul>
                <?php foreach ($_additional as $_data) : ?>

                    <li class="col label"><span><?= $block->escapeHtml($_data['label']) ?></span> <?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></li>

                <?php endforeach; ?>
            </ul>
        </table>


    </div>



<?php endif; ?>