<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $stockCount = $_product->getExtensionAttributes()->getStockItem()->getQty(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>

                <div class="counter-flex-container">
                    <div class="field qty">
                        <!-- <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label> -->
                        <div class="control">
                            <input type="number" name="qty" id="qty" min="0" value="<?= $block->getProductDefaultQty() * 1 ?>" title="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="input-text qty" data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" />
                        </div>
                    </div>


                    <!-- stock availability -->
                    <?php if ($_product->isAvailable()) : ?>
                        <div class="stock-available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                            <span><?= $block->escapeHtml(__('IN STOCK')) ?></span>
                        </div>
                    <?php else : ?>
                        <div class="stock-unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                            <span><?= $block->escapeHtml(__('OUT OF STOCK')) ?></span>
                        </div>
                    <?php endif; ?>
                    <p><?= $stockCount ?> Items available</p>
                    <!-- stock availability -->
                </div>


            <?php endif; ?>





            <div class="actions">
                <button type="submit" title="<?= $block->escapeHtmlAttr($buttonTitle) ?>" class="action primary tocart" id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>